### PR TITLE
WIP: add submitblock API

### PR DESCRIPTION
**Pull request by HAOYUatHZ**

### CODE REVIEW

**Comment by SebastianElvis** [comment]
Could you make this PR from branch `dev` rather than `proto-no-blockgen` as now this repo focuses on the production-ready version?

**Comment by HAOYUatHZ** [comment]
> Could you make this PR from branch `dev` rather than `proto-no-blockgen` as now this repo focuses on the production-ready version?

You are right.

And additionally we need to add some missing improvements to dev branch, (e.g., https://github.com/rand-chain/rust-randchain/blob/62fae93ec800cb18d4ea0fe16bdc2a1ec779be4d/network/src/network.rs#L87-L90)

like in https://github.com/rand-chain/rust-randchain/blob/10edbfd3835e32c2821360c5afbad8001a4505ce/network/src/network.rs#L86-L134

**Comment by SebastianElvis** [comment]
Thanks for pointing out. We may need to cherry-pick such changes to `master`.
I have opened #121 for this issue.

**Comment by HAOYUatHZ** [comment]
fix:
+ [ ] bits
+ [ ] curtime
+ [ ] height

Still need to check:
+ [ ] previousblockhash (if reverse seems ok)
+ [ ] target

**Pull request closed without merging**
